Sync with portage [Wed Feb  8 09:18:06 MSK 2012].

diff --git a/mail-filter/amavisd-new/files/amavisd.initd b/mail-filter/amavisd-new/files/amavisd.initd
--- a/mail-filter/amavisd-new/files/amavisd.initd
+++ b/mail-filter/amavisd-new/files/amavisd.initd
@@ -1,13 +1,13 @@
 #!/sbin/runscript
-# Copyright 1999-2012 Gentoo Foundation
+# Copyright 1999-2010 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /var/cvsroot/gentoo-x86/mail-filter/amavisd-new/files/amavisd.initd,v 1.4 2012/01/10 13:46:47 eras Exp $
+# $Header: /var/cvsroot/gentoo-x86/mail-filter/amavisd-new/files/amavisd.initd,v 1.2 2010/12/07 10:34:32 eras Exp $
 
-extra_started_commands="reload"
-extra_commands="debug debug_sa"
+opts="${opts} reload debug debug_sa"
 
 prog="/usr/sbin/amavisd"
 progname="amavisd-new"
+conffile="/etc/amavisd.conf"
 
 depend() {
 	need net
@@ -15,8 +15,23 @@ depend() {
 	before mta
 }
 
+checkconfig() {
+	local piddir pidfile
+	if [ -r "${conffile}" ] ; then
+		pidfile=$(grep -m1 ^[^#].*pid_file "${conffile}"|sed -e 's/.*"\(.*\)".*/\1/')
+		piddir=${pidfile%/*}
+		if [ ! -d "${piddir:-/var/amavis}" ] ; then
+			checkpath -q -d -o root:amavis -m 0770 "${piddir}" || return 1
+		fi
+	else
+		eerror "Missing conf file."
+		return 1
+	fi
+}
+
 start() {
 	ebegin "Starting ${progname}"
+	checkconfig || return 1
 	"${prog}" start
 	eend $?
 }
@@ -43,12 +58,14 @@ restart() {
 
 debug() {
 	ebegin "Starting ${progname} in debug mode"
+	checkconfig || return 1
 	"${prog}" debug
 	eend $?
 }
 
 debug_sa() {
 	ebegin "Starting ${progname} in debug-sa mode"
+	checkconfig || return 1
 	"${prog}" debug-sa
 	eend $?
 }
