Sync with portage [Wed Oct  1 16:52:21 MSK 2014].

diff --git a/net-misc/hylafaxplus/files/hylafaxplus-init b/net-misc/hylafaxplus/files/hylafaxplus-init
--- a/net-misc/hylafaxplus/files/hylafaxplus-init
+++ b/net-misc/hylafaxplus/files/hylafaxplus-init
@@ -107,66 +107,70 @@ checkconfig() {
 start() {
 	local result
 
-	checkconfig || return #!/sbin/runscript
-# Copyright 1999-2012 Gentoo Foundation
-# Author Geaaru
-# Distributed under the terms of the GNU General Public License v2
+	checkconfig || return 1
 
-opts="zap"
+	ebegin "Starting HylaFAX server daemons"
 
-depend() {
-	use lo
+	start_faxq
+	result=$?
+
+	if [ $result -ne 0 ]  ; then
+		eerror "Error on start $faxq daemon"
+		return 1
+	fi
+
+	start_hfaxd
+	result=$?
+
+	eend $result
 }
 
-checkconfig() {
-	ebegin "Check hylafax server configuration..."
+start_hfaxd() {
+	local arguments="--start \
+			 --make-pidfile --pidfile $PIDDIR/hfaxd.pid"
+	
+	einfo "Starting $hfaxd with args $hfaxd_args"
 
-	if [ x$spooldir == x ] ; then
-		eerror "No spooldir directory defined"
-		return 1
-	else
-		SPOOL=$spooldir
-		einfo "Use spool directory $SPOOL"
+	start-stop-daemon -b ${arguments} --exec $hfaxd -- $hfaxd_args > /dev/null 2>&1
+
+	return $?;
+}
+
+start_faxq() {
+	local arguments="--start \
+			 --make-pidfile --pidfile $PIDDIR/faxq.pid"
+	einfo "Starting $faxq ... "
+
+	start-stop-daemon -b ${arguments} --exec $faxq -- $faxq_args > /dev/null 2>&1
+	
+	return $?
+}
+
+stop() {
+	checkconfig || return 1
+
+	ebegin "Stopping HylaFAX server daemons"
+	
+	start-stop-daemon --stop --quiet --pidfile $PIDDIR/hfaxd.pid
+	start-stop-daemon --stop --quiet --pidfile $PIDDIR/faxq.pid
+	eend $?
+}
+
+zap() {
+	checkconfig || return 1
+
+	ebegin "Zap HylaFAX server daemon files"
+
+	if [ -f $PIDFILE/hfaxd.pid ] ; then
+		rm -f $PIDFILE/hfaxd.pid
 	fi
 
-	if [ x$mode == x ] ; then
-		eerror "No mode defined"
-		return 1
+	if [ -f $PIDFILE/faxq.pid ] ; then
+		rm -f $PIDFILE/faxq.pid
 	fi
+}
 
-	if [ ! -f $SPOOL/etc/setup.cache ] ; then
-		eerror "No $SPOOL/etc/setup.cache file founded. Use faxsetup command"
-		return 1
-	fi
-
-	if [[ x$hfaxd == x || ! -f $hfaxd ]] ; then
-		eerror "No hfaxd daemon founded"
-		return 1
-	fi
-
-	if [[ x$faxq == x || ! -f $faxq ]] ; then
-		eerror "No faxq program founded"
-		return 1
-	fi
-
-	if [[ x$faxgetty == x || ! -f $faxgetty ]] ; then
-		eerror "No faxgetty program founded"
-		return 1
-	fi
-
-	if [ x$faxbind == x ] ; then
-		eerror "No binding address supply"
-		return 1
-	fi
-
-	if [ x$piddir == x ] ; then
-		PIDDIR=$SPOOL
-	else
-		PIDDIR=$piddir
-	fi
-
-
-	hfaxd_args="-l $faxbind -q $SPOOL"
-
-	case $mode in
-		newproto)
+restart() {
+	stop
+	start
+}
